title = "CmdrX"
gitRepoUrl = "https://github.com/BiraruX/CmdrX"
gitSourceBranch = "main"
changelog = true

classOrder = [
  "Cmdr",
  "CmdrClient",

  "Registry",
  "Dispatcher",
  "Util",

  "CommandContext",
  "ArgumentContext",
]

[docusaurus]
organizationName = "BiraruX"
projectName = "CmdrX"
deploymentBranch = "gh-pages"
tagline = "Extensible command console for Roblox developers. This fork was made to add small use cases that 'arent fit for production code'"
titleDelimiter = "â€¢"

baseUrl = "/Cmdr/beta/"

# TODO: Remove when releasing new website
noIndex = true

[home]
enabled = true
includeReadme = false

[navbar]
title = ""

[navbar.logo]
alt = "CmdrX"
src = "/logo.png"

[[navbar.items]]
href = "https://github.com/BiraruX/CmdrX/releases"
label = "Releases"
position = "right"

[[navbar.items]]
href = "https://discord.gg/g5PdMxh"
label = "Discord"
position = "right"

[footer]
copyright = "Built using Docusaurus and Moonwave. Released under the <a href=\"https://github.com/BiraruX/CmdrX/blob/master/LICENSE\" target=\"_blank\">MIT License</a>."

[[footer.links]]
title = "Learn"
[[footer.links.items]]
label = "Introduction"
href = "/docs/intro"
[[footer.links.items]]
label = "Best practice"
href = "/docs/advanced/bestpractice"
[[footer.links.items]]
label = "API reference"
href = "/api/Cmdr"
[[footer.links.items]]
label = "Changelog"
href = "/changelog"

[[footer.links]]
title = "Community"
[[footer.links.items]]
label = "Contribute"
href = "/docs/contribute"
[[footer.links.items]]
label = "Security"
href = "/docs/community/securityreport"
[[footer.links.items]]
label = "Discord"
href = "https://discord.gg/g5PdMxh"
[[footer.links.items]]
label = "Bug tracker"
href = "https://github.com/BiraruX/CmdrX/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc"
